x-common-exercise: &common-exercise
  build:
    context: .
  deploy:
    resources:
      limits:
        cpus: '0.50'
        memory: 500M
  

services:
  exercise1:
    <<: *common-exercise
    build:
      target: ex1
      tags: ["ex1:latest"]

  exercise2:
    <<: *common-exercise
    build:
      context: .
      target: ex2

  exercise3:
    <<: *common-exercise
    build:
      target: ex3
      tags: ["ex3:latest"]

  exercise4:
    <<: *common-exercise
    build:
      target: ex4
      tags: ["ex4:latest"]

  exercise5:
    <<: *common-exercise
    build:
      target: ex5
      tags: ["ex5:latest"]

  exercise6:
    <<: *common-exercise
    build:
      target: ex6
      tags: ["ex6:latest"]

  exercise7:
    <<: *common-exercise
    build:
      target: ex7
      tags: ["ex7:latest"]

  exercise8:
    <<: *common-exercise
    build:
      target: ex8
      tags: ["ex8:latest"]
